language: python
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.5
python:
  - "2.6"
  - "2.7"
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install . --use-mirrors
script: ./test_project/manage.py test
