language: python
env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install . --use-mirrors
script: ./test_project/manage.py test
